// Auto-generated file - DO NOT EDIT
// Generated by @solo-labs/utils generate-index
// To regenerate, run: npx nx run @solo-labs/agents-agnostic:generate-index

// Agent types
type Agent =
  | 'aegis-architect'
  | 'agent-capability-analyst'
  | 'agent-optimizer'
  | 'agent-orchestrator'
  | 'cicd-agent'
  | 'code-explainer'
  | 'code-generator'
  | 'commit-message-generator'
  | 'context-loader'
  | 'debug-assistant'
  | 'doc-writer'
  | 'foundry-test-writer'
  | 'infrastructure-agent'
  | 'l-unit-accountant'
  | 'migration-assistant'
  | 'performance-analyzer'
  | 'plan-reviewer'
  | 'planner'
  | 'pr-creator'
  | 'pr-reviewer'
  | 'prompt-engineer'
  | 'refactorer'
  | 'researcher'
  | 'security-analyzer'
  | 'stack-splitter'
  | 'style-enforcer'
  | 'test-runner'
  | 'test-writer';

type Agents = {
  [key in Agent]: {
    description: string;
    filePath: string;
  };
};

// Export agents with descriptions and file paths
export const agents: Agents = {
  'aegis-architect': {
    description:
      'Protocol architecture specialist for AegisEngine - designs vault lifecycle, session management, and understands three-layer execution model',
    filePath: './aegis-architect.md',
  },
  'agent-capability-analyst': {
    description:
      'Advanced specialist in AI agent capability analysis with enhanced scoring algorithms, semantic matching for natural language tasks, and team composition recommendations for complex workflows',
    filePath: './agent-capability-analyst.md',
  },
  'agent-optimizer': {
    description:
      'Meta-agent that analyzes, optimizes, and continuously improves the performance of other AI agents through systematic refinement strategies',
    filePath: './agent-optimizer.md',
  },
  'agent-orchestrator': {
    description:
      'Intelligent orchestrator that coordinates other AI agents for complex software development workflows, matching tasks to specialists based on capabilities',
    filePath: './agent-orchestrator.md',
  },
  'cicd-agent': {
    description:
      'CI/CD pipeline specialist for automated deployment setup, workflow configuration, and release management',
    filePath: './cicd-agent.md',
  },
  'code-explainer': {
    description:
      'Explains code functionality, patterns, and design decisions in clear, accessible language',
    filePath: './code-explainer.md',
  },
  'code-generator': {
    description:
      'Comprehensive code generation specialist that creates production-ready code with tests, following best practices and existing patterns',
    filePath: './code-generator.md',
  },
  'commit-message-generator': {
    description:
      'Generates clear, conventional commit messages following project standards',
    filePath: './commit-message-generator.md',
  },
  'context-loader': {
    description:
      'Advanced context management system for deep codebase understanding, intelligent summarization, and cross-agent context sharing.',
    filePath: './context-loader.md',
  },
  'debug-assistant': {
    description:
      'Helps diagnose and fix bugs through systematic debugging techniques',
    filePath: './debug-assistant.md',
  },
  'doc-writer': {
    description:
      'Generates clear, comprehensive documentation for code, APIs, and systems',
    filePath: './doc-writer.md',
  },
  'foundry-test-writer': {
    description:
      'Foundry test generation specialist - creates unit tests, fuzz tests, invariant tests, and integration tests for Solidity contracts',
    filePath: './foundry-test-writer.md',
  },
  'infrastructure-agent': {
    description:
      'Infrastructure automation specialist for cloud architecture, scaling strategies, and cost optimization',
    filePath: './infrastructure-agent.md',
  },
  'l-unit-accountant': {
    description:
      'L-unit math and equity calculation specialist - validates equity-neutral operations, debugs share price calculations, ensures PIPS precision',
    filePath: './l-unit-accountant.md',
  },
  'migration-assistant': {
    description:
      'Migration specialist for guiding version upgrades, compatibility checking, rollback strategies, and validation steps',
    filePath: './migration-assistant.md',
  },
  'performance-analyzer': {
    description:
      'Comprehensive performance analysis agent for identifying bottlenecks, analyzing complexity, and providing optimization strategies with measurable impact estimates',
    filePath: './performance-analyzer.md',
  },
  'plan-reviewer': {
    description:
      'Reviews implementation plans for completeness, correctness, and alignment with codebase patterns',
    filePath: './plan-reviewer.md',
  },
  planner: {
    description:
      'Create clear, actionable implementation plans without writing code',
    filePath: './planner.md',
  },
  'pr-creator': {
    description:
      'Creates or updates Graphite PRs with auto-generated conventional commit messages and comprehensive PR descriptions based on diffs',
    filePath: './pr-creator.md',
  },
  'pr-reviewer': {
    description:
      'Reviews pull requests for code quality, correctness, security, and adherence to best practices',
    filePath: './pr-reviewer.md',
  },
  'prompt-engineer': {
    description:
      'Expert in analyzing, optimizing, and testing prompts for AI agents and LLMs to maximize clarity, effectiveness, and efficiency',
    filePath: './prompt-engineer.md',
  },
  refactorer: {
    description:
      'Identifies refactoring opportunities and provides safe, incremental refactoring plans',
    filePath: './refactorer.md',
  },
  researcher: {
    description:
      'Conduct comprehensive research including architectural patterns, technology comparison, security analysis, and codebase pattern extraction.',
    filePath: './researcher.md',
  },
  'security-analyzer': {
    description:
      'Comprehensive security analysis agent for vulnerability assessment, threat modeling, and compliance checking',
    filePath: './security-analyzer.md',
  },
  'stack-splitter': {
    description:
      'Semantic analysis agent for splitting monolithic branches into logical, reviewable PR stacks. Analyzes git history, file changes, and code semantics to propose optimal split boundaries.',
    filePath: './stack-splitter.md',
  },
  'style-enforcer': {
    description:
      'Advanced style and convention enforcement with multi-language support, pattern detection, automated fixes, and comprehensive reporting.',
    filePath: './style-enforcer.md',
  },
  'test-runner': {
    description:
      'Automated agent testing specialist that validates agent behaviors, tests prompt variations, detects regressions, and provides comprehensive test reporting with performance metrics.',
    filePath: './test-runner.md',
  },
  'test-writer': {
    description:
      'Generate comprehensive, deterministic tests with advanced testing strategies, scenario generation, and edge case identification.',
    filePath: './test-writer.md',
  },
} as const;

export type AgentName = keyof typeof agents;
