// Auto-generated file - DO NOT EDIT
// Generated by @solo-labs/utils generate-index
// To regenerate, run: npx nx run @solo-labs/commands-agnostic:generate-index

type CommandName =
  | 'address-pr-issues'
  | 'analyze-session'
  | 'auto-spec'
  | 'create-pr'
  | 'debug-collateral'
  | 'debug-l-units'
  | 'deploy'
  | 'execute-plan'
  | 'explain-file'
  | 'explore'
  | 'explore-aegis'
  | 'fix-bug'
  | 'gen-foundry-tests'
  | 'gen-tests'
  | 'generate-commit-message'
  | 'implement-spec'
  | 'monitor'
  | 'perf-analyze'
  | 'plan'
  | 'refactor'
  | 'research'
  | 'review-code'
  | 'review-keeper-flow'
  | 'review-plan'
  | 'review-pr'
  | 'split-stack'
  | 'validate-invariants'
  | 'work-through-pr-comments';

export type Commands = {
  [key in CommandName]: {
    description: string;
    filePath: string;
  };
};

export const commands: Commands = {
  'address-pr-issues': {
    description: 'Reviews a GitHub PR, addresses comments, and fixes CI issues',
    filePath: './address-pr-issues.md',
  },
  'analyze-session': {
    description:
      'Analyze EIP-1153 session flows, transient storage usage, and phase execution',
    filePath: './analyze-session.md',
  },
  'auto-spec': {
    description:
      'Autonomously create and implement a complete spec workflow with multi-agent collaboration, bypassing manual review steps through intelligent consensus-building',
    filePath: './auto-spec.md',
  },
  'create-pr': {
    description:
      'Create or update a Graphite PR with auto-generated conventional commit messages and comprehensive descriptions based on code diffs.',
    filePath: './create-pr.md',
  },
  'debug-collateral': {
    description:
      'Debug sqrt(K) floor calculations, solvency checks, and collateral requirements',
    filePath: './debug-collateral.md',
  },
  'debug-l-units': {
    description:
      'Debug L-unit accounting issues - trace flows, validate equity neutrality, check precision',
    filePath: './debug-l-units.md',
  },
  deploy: {
    description:
      'Orchestrate deployment pipelines, infrastructure setup, and CI/CD configuration using specialized deployment agents.',
    filePath: './deploy.md',
  },
  'execute-plan': {
    description: 'Execute an approved implementation plan step by step',
    filePath: './execute-plan.md',
  },
  'explain-file': {
    description:
      'Comprehensive code explanation using multi-agent analysis for architecture, patterns, security, and performance insights.',
    filePath: './explain-file.md',
  },
  explore: {
    description:
      'Deep dive into a codebase area to build comprehensive understanding before creating and implementing a plan.',
    filePath: './explore.md',
  },
  'explore-aegis': {
    description:
      'Deep dive into AEGIS protocol architecture with domain-specific analysis',
    filePath: './explore-aegis.md',
  },
  'fix-bug': {
    description: 'Diagnose and fix bugs through systematic debugging',
    filePath: './fix-bug.md',
  },
  'gen-foundry-tests': {
    description:
      'Generate Foundry tests for Solidity contracts - unit, fuzz, invariant, and integration tests',
    filePath: './gen-foundry-tests.md',
  },
  'gen-tests': {
    description:
      'Generate comprehensive tests for code based on framework detection',
    filePath: './gen-tests.md',
  },
  'generate-commit-message': {
    description:
      'Generate a structured git commit message based on current changes and repository patterns',
    filePath: './generate-commit-message.md',
  },
  'implement-spec': {
    description:
      'Orchestrate implementation of spec-workflow tasks using intelligent agent coordination, parallel execution, and quality gates.',
    filePath: './implement-spec.md',
  },
  monitor: {
    description:
      'Set up comprehensive monitoring for applications with automated metrics identification, alerting, and dashboard configuration',
    filePath: './monitor.md',
  },
  'perf-analyze': {
    description:
      'O(1) Chain-of-Thought Performance Analyzer - Systematic complexity analysis with optimization paths, bottleneck identification, and performance proofs',
    filePath: './perf-analyze.md',
  },
  plan: {
    description:
      'Create clear, actionable implementation plans for any task, feature, refactor, or architectural change through collaborative multi-agent refinement',
    filePath: './plan.md',
  },
  refactor: {
    description: 'Identify and apply safe refactoring improvements to code',
    filePath: './refactor.md',
  },
  research: {
    description:
      'Research a topic using web search, documentation, and codebase analysis',
    filePath: './research.md',
  },
  'review-code': {
    description:
      'Review code for quality, patterns, and potential issues without a PR context',
    filePath: './review-code.md',
  },
  'review-keeper-flow': {
    description:
      'Analyze peel and micro-liquidation implementations for correctness and incentives',
    filePath: './review-keeper-flow.md',
  },
  'review-plan': {
    description:
      'Review an implementation plan for completeness, correctness, and alignment with codebase patterns',
    filePath: './review-plan.md',
  },
  'review-pr': {
    description:
      'Review a pull request for code quality, correctness, and best practices',
    filePath: './review-pr.md',
  },
  'split-stack': {
    description:
      'Automatically split a monolithic branch with many changes into a logical, reviewable stack of PRs using semantic analysis and Graphite.',
    filePath: './split-stack.md',
  },
  'validate-invariants': {
    description: 'Check code against AEGIS spec invariants and safety rules',
    filePath: './validate-invariants.md',
  },
  'work-through-pr-comments': {
    description:
      'Methodically work through GitHub pull request comments in a conversational workflow, analyzing each comment, presenting solution options, gathering your decisions, and implementing approved changes.',
    filePath: './work-through-pr-comments.md',
  },
} as const;
