// Auto-generated file - DO NOT EDIT
// Generated by @solo-labs/utils generate-index
// To regenerate, run: npx nx run @solo-labs/agents-subgraph:generate-index

type CommandName = 'assemblyscript-expert' | 'subgraph-developer';

export type Commands = {
  [key in CommandName]: {
    description: string;
    filePath: string;
  };
};

export const commands: Commands = {
  'assemblyscript-expert': {
    description:
      'Specialist in AssemblyScript for The Graph subgraph development with performance optimization',
    filePath: './assemblyscript-expert.md',
  },
  'subgraph-developer': {
    description:
      'Expert in The Graph Protocol subgraph development for AEGIS Protocol indexing',
    filePath: './subgraph-developer.md',
  },
} as const;
