// Auto-generated file - DO NOT EDIT
// Generated by @solo-labs/utils generate-index
// To regenerate, run: npx nx run @solo-labs/commands-frontend:generate-index

type CommandName = 'analyze-vault-flow' | 'explore-redux' | 'gen-component';

export type Commands = {
  [key in CommandName]: {
    description: string;
    filePath: string;
  };
};

export const commands: Commands = {
  'analyze-vault-flow': {
    description: 'Trace vault interaction flows from UI to contract execution',
    filePath: './analyze-vault-flow.md',
  },
  'explore-redux': {
    description:
      'Analyze Redux store structure and vault state management patterns',
    filePath: './explore-redux.md',
  },
  'gen-component': {
    description:
      'Generate AEGIS-specific React components with L-unit display and vault integration',
    filePath: './gen-component.md',
  },
} as const;
