// Auto-generated file - DO NOT EDIT
// Generated by @solo-labs/utils generate-index
// To regenerate, run: npx nx run @solo-labs/commands-subgraph:generate-index

type CommandName = 'gen-matchstick-tests' | 'gen-subgraph-handler';

export type Commands = {
  [key in CommandName]: {
    description: string;
    filePath: string;
  };
};

export const commands: Commands = {
  'gen-matchstick-tests': {
    description:
      'Generate Matchstick unit tests for AEGIS subgraph event handlers',
    filePath: './gen-matchstick-tests.md',
  },
  'gen-subgraph-handler': {
    description:
      'Generate AssemblyScript event handlers for AEGIS Protocol subgraph indexing',
    filePath: './gen-subgraph-handler.md',
  },
} as const;
