// Auto-generated file - DO NOT EDIT
// Generated by @solo-labs/utils generate-index
// To regenerate, run: npx nx run @solo-labs/agents-frontend:generate-index

// Agent types
type Agent =
  | 'graphql-expert'
  | 'redux-architect'
  | 'vault-ui-builder'
  | 'web3-integrator';

type Agents = {
  [key in Agent]: {
    description: string;
    filePath: string;
  };
};

// Export agents with descriptions and file paths
export const agents: Agents = {
  'graphql-expert': {
    description:
      'Design GraphQL queries and Apollo Client integration for aegis-engine-subgraph',
    filePath: './graphql-expert.md',
  },
  'redux-architect': {
    description:
      'Design and optimize Redux state management for AEGIS vault interactions',
    filePath: './redux-architect.md',
  },
  'vault-ui-builder': {
    description:
      'Build vault management UI components with proper L-unit display and LTV visualization',
    filePath: './vault-ui-builder.md',
  },
  'web3-integrator': {
    description: 'Integrate wagmi/viem hooks with AEGIS contract interactions',
    filePath: './web3-integrator.md',
  },
} as const;

export type AgentName = keyof typeof agents;
